I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mystery1.rpy", line 48, in script
    call screen mystery1_investigation
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/mystery1.rpy", line 169, in execute
    screen mystery1_person():
  File "game/mystery1.rpy", line 169, in execute
    screen mystery1_person():
  File "game/mystery1.rpy", line 171, in execute
    frame:
  File "game/mystery1.rpy", line 174, in execute
    vbox:
  File "game/mystery1.rpy", line 176, in execute
    textbutton "닫기" action [
  File "game/mystery1.rpy", line 176, in keywords
    textbutton "닫기" action [
  File "game/mystery1.rpy", line 177, in <module>
    SetDict(investigation_state, person, True),
NameError: name 'person' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mystery1.rpy", line 48, in script
    call screen mystery1_investigation
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1980, in execute
    self.call("execute")
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1959, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\exports\statementexports.py", line 345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\NFSA\Downloads\renpy-8.3.4-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/mystery1.rpy", line 169, in execute
    screen mystery1_person():
  File "game/mystery1.rpy", line 169, in execute
    screen mystery1_person():
  File "game/mystery1.rpy", line 171, in execute
    frame:
  File "game/mystery1.rpy", line 174, in execute
    vbox:
  File "game/mystery1.rpy", line 176, in execute
    textbutton "닫기" action [
  File "game/mystery1.rpy", line 176, in keywords
    textbutton "닫기" action [
  File "game/mystery1.rpy", line 177, in <module>
    SetDict(investigation_state, person, True),
NameError: name 'person' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
go2manga 1.0
Tue Jan 21 21:17:54 2025
